/**
 * FootPal FC's verifiable figures, counted from the repository itself.
 *
 * DO NOT hand-edit the numbers here or anywhere they appear in copy. They are
 * generated by `npm run sync:footpal`, which counts them over a real checkout of
 * Amiros3000/FootPal-FC, and a GitHub Action re-runs that weekly. Typing a
 * number into a sentence is how the site ended up quoting a v2.43.0 release and
 * a 175-test suite for a month after they became v2.88.6 and 399.
 *
 * Everything a page or the chatbot says about FootPal's size should interpolate
 * from here, so one sync moves the hero, the OG image, the resume, and every
 * chatbot answer at once.
 */
import metrics from "@/content/footpal-metrics.json";

export const footpal = metrics;

/**
 * The figures as they are spoken in prose, so the same claim reads identically
 * everywhere and there is exactly one place to change the phrasing.
 */
export const footpalFigures = {
  models: `${metrics.models}`,
  handlers: `${metrics.handlers}`,
  routeFiles: `${metrics.routeFiles}`,
  testBlocks: `${metrics.testBlocks}`,
  testSuites: `${metrics.testSuites}`,
  commits: `${metrics.commits}`,
  release: `v${metrics.version}`,
  buildingSince: metrics.buildingSince,
  /** Not counted — see the `manual` block in content/footpal-metrics.json. */
  activePlayers: metrics.manual.activePlayers,
  crews: metrics.manual.crews,
} as const;

/** "27 Postgres models, 119 HTTP handlers, and 399 test blocks" */
export const footpalScaleSentence =
  `${metrics.models} Postgres models, ${metrics.handlers} HTTP handlers, ` +
  `and ${metrics.testBlocks} test blocks`;

/** The day the figures were last counted. Replaces the old fixed audit date. */
export const footpalCountedOn = new Date(
  `${metrics.generatedAt}T00:00:00Z`,
).toLocaleDateString("en-US", {
  month: "long",
  day: "numeric",
  year: "numeric",
  timeZone: "UTC",
});
