/**
 * FootPal FC — flagship project detail.
 *
 * Every figure here is DERIVED, not typed. content/footpal-audit.json is
 * generated by scripts/audit-footpal.mjs from a FootPal FC checkout:
 *
 *   npm run audit:footpal -- /path/to/footpal-fc
 *
 * Do not edit the numbers by hand. They were hand-typed once, across four
 * files, and by the second audit every one of them was wrong: the page claimed
 * 109 handlers / 175 tests / 457 commits / v2.43.0 while the repo was at
 * 119 / 416 / 585 / v2.89.2.
 *
 * The prose below is hand-written and stays that way. Nothing in it may be
 * softened into a claim the code does not support. In particular: the service
 * worker is an OFFLINE FALLBACK, never "offline support" and never "works
 * offline" — it caches nothing, by design.
 */
import audit from "@/content/footpal-audit.json";

/** "2026-09-04" -> "September 4, 2026". Parsed as UTC so the date cannot
 *  drift a day backwards when rendered west of Greenwich. */
function formatAuditDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}

export const FOOTPAL_AUDIT_DATE = formatAuditDate(audit.auditDate);

/**
 * Fills `{models}`, `{handlers}`, `{routeFiles}`, `{testBlocks}`, `{testSuites}`,
 * `{commits}`, `{version}` in copy that quotes a count in prose.
 *
 * Applied at the render site, never inside getPortfolioContent(), so the stored
 * content stays a template. Filling on read would mean the admin editor loads
 * interpolated text and saves the frozen numbers back over the placeholders.
 *
 * An unknown placeholder is left alone rather than replaced with "undefined":
 * a visible `{typo}` is a bug someone fixes, silent wrong output is not.
 */
const PLACEHOLDER_VALUES: Record<string, string | number> = {
  models: audit.models,
  handlers: audit.handlers,
  routeFiles: audit.routeFiles,
  testBlocks: audit.testBlocks,
  testSuites: audit.testSuites,
  commits: audit.commits,
  version: audit.version,
  buildingSince: audit.buildingSince,
  auditDate: audit.auditDate,
  /** "September 4, 2026" — for prose, where the ISO form reads wrong. */
  auditDateLong: FOOTPAL_AUDIT_DATE,
};

export function fillAuditPlaceholders(text: string): string {
  return text.replace(/\{(\w+)\}/g, (whole, key: string) =>
    key in PLACEHOLDER_VALUES ? String(PLACEHOLDER_VALUES[key]) : whole,
  );
}

export type SpecFigure = {
  value: string;
  label: string;
};

/**
 * Verified counts, rendered as static text — never animated up from a zero
 * state. The previous stat row derived its number from an animation's starting
 * value and shipped a literal "0+" whenever that animation didn't run.
 */
export const footpalSpec: SpecFigure[] = [
  { value: String(audit.models), label: "Postgres models" },
  {
    value: String(audit.handlers),
    label: `HTTP handlers across ${audit.routeFiles} route files`,
  },
  {
    value: String(audit.testBlocks),
    label: `test blocks across ${audit.testSuites} suites`,
  },
  { value: String(audit.commits), label: "commits" },
  { value: `v${audit.version}`, label: "current release" },
];

/**
 * Hero strip. Deliberately carries only what the headline and subheadline do
 * not already say — the release state, not the counts.
 */
export const footpalRelease: SpecFigure[] = [
  { value: `v${audit.version}`, label: "current release" },
  { value: String(audit.commits), label: "commits" },
  { value: audit.buildingSince, label: "building since" },
];

/**
 * The same three figures as one line, for the OG card.
 *
 * Written out rather than joining footpalRelease's value/label pairs: those
 * read as "<value> <label>" because the hero renders the label as a trailing
 * mono suffix, and joining them naively produced "Jun 2026 building since".
 */
export const footpalReleaseLine = `v${audit.version} · ${audit.commits} commits · building since ${audit.buildingSince}`;

export const footpalStack = [
  "Next.js 15",
  "TypeScript",
  "PostgreSQL (Neon)",
  "Prisma",
  "Web Push",
  "Sentry",
  "Vercel",
];

export type Decision = {
  /** Leads with what was built. Never a problem statement or a characterization. */
  title: string;
  body: string;
  /** What the choice cost. The page's argument is that every decision has one. */
  tradeoff: string;
};

export const footpalDecisions: Decision[] = [
  {
    title: "Crew-scoped isolation enforced in the application layer",
    body: "Independent crews share one database. Access is gated by explicit guard functions — canAccessGame, canManageGame, getUserCrew — invoked per route.",
    tradeoff:
      "No Postgres RLS and no Prisma middleware. Isolation depends on each crew-scoped route calling a guard, and nothing underneath catches one that skips it.",
  },
  {
    title: "Session auth written from scratch, no auth library",
    body: "The cookie carries the plaintext token; the database stores only the SHA-256 hash. Sessions are per-device. A three-tier resolution path — Session row, then legacy hash column, then legacy plaintext — migrated existing accounts on read, without logging anyone out.",
    tradeoff: "Three lookup paths to maintain instead of one.",
  },
  {
    title: "Man-of-the-match awards that fire exactly once",
    body: "The award can be triggered by the final vote or by a fallback cron. Both paths run one conditional update guarded on a null timestamp, and the affected-row count decides which trigger won.",
    tradeoff:
      "The guarantee lives in one UPDATE's WHERE clause and its affected-row count, so it holds only as long as that stays a single statement.",
  },
  {
    title: "Batched the game page's reads, cutting load from ~3.3s to ~1.1s",
    body: "Collapsed 8 sequential Prisma reads into one parallel fetch and moved stats computation off first paint, then added three indexes after EXPLAIN showed sequential scans.",
    tradeoff:
      "Measured by hand on the heaviest crew game. There is no benchmark harness, so this is a point measurement, not continuous tracking.",
  },
  {
    title: "Kickoff times resolved to UTC without a date library",
    body: "Crew-local kickoff times resolve to UTC instants through Intl.DateTimeFormat.formatToParts, so daylight-saving shifts land on the right instant. package.json contains zero date libraries.",
    tradeoff:
      "The conversion logic is mine rather than a library's, including the DST transition days when a local time either does not exist or happens twice.",
  },
  {
    title: "Hand-written service worker serving a branded offline page",
    body: "The service worker is written by hand rather than generated. It serves a branded offline page in place of the browser's error screen. It does not cache pages, API responses, or app JS.",
    tradeoff:
      "Deliberate. Caching rosters and costs would show people stale information, so there is no cached app to fall back on — offline gets a clear page, not a working one.",
  },
  {
    title: "Ratings and cost settlement as pure, unit-tested modules",
    body: "The rating engine is crew-relative: each stat scales against that crew's best player and decays with absence. The settlement module nets per-game cost shares down to a single balance per player pair. Both are pure functions covered by the test suites.",
    tradeoff:
      "Crew-relative ratings do not compare across crews — the same number means different things in different crews.",
  },
  {
    title: "Every Sentry event through one PII-scrubbing chokepoint",
    body: "All error reporting routes through a single scrubbing function before anything leaves the app.",
    tradeoff:
      "Centralizing the scrubbing means one place to audit, and one place every error path has to keep routing through.",
  },
];
